export const image_root_dir = 'https://storage.codefast.tech'
export const NEWSPOST_HOST = 'https://node.sarkarimail.com'
export const SARKAARIEXAMS_HOST = 'https://spring.sarkarimail.com' 
//export const NEWSPOST_HOST = 'http://localhost:8082'
//export const SARKAARIEXAMS_HOST = 'http://localhost:8081' 
export const GOOGLE_RECAPTCHA_SITE_KEY= '6LcV5yIkAAAAAEnlu8PeMl_aSdjroE_FYFDD9zv7'
//export const GOOGLE_RECAPTCHA_SITE_KEY='6Lf3GjkjAAAAAEu4kyomzf7mkl4lerBSkTNnefGR'
export const MAIN_COLOR_CODE = '#077df1';
export const SECONDRY_COLOR = '#639fda';
export const NEWSPOSTS_ALL = '/posts/all';
export const DOMAIN = 'https://rojgaralerts.in'